export const TERMINAL_SCHEME_SOURCE = [
    // T1
    { terminal: 'T1', range: 'H5:U5', label: 'D2' },
    { terminal: 'T1', range: 'H6:Q10', label: 'КТЦ №1 / Уголная' },
    { terminal: 'T1', range: 'R6:U10', label: 'КТЦ / Газовая' },
    { terminal: 'T1', range: 'G8:G10', label: 'G1' },
    { terminal: 'T1', range: 'H11:Q12', label: 'РМУ / 1 этаж' },
    { terminal: 'T1', range: 'H13:Q13', label: 'Компрессорная' },
    { terminal: 'T1', range: 'H14:Q14', label: 'С1' },
    { terminal: 'T1', range: 'W14:W22', label: 'D1 /' },
    { terminal: 'T1', range: 'X14:AY14', label: 'D1 /' },
    { terminal: 'T1', range: 'AZ14:AZ22', label: 'D1 /' },
    { terminal: 'T1', range: 'H15:L17', label: 'ЛБП Тестомес / (3 этаж)' },
    { terminal: 'T1', range: 'M15:Q17', label: 'ЛБП Кабинеты (3 этаж)' },
    { terminal: 'T1', range: 'X15:AA15', label: 'G1' },
    { terminal: 'T1', range: 'AB15:AE15', label: 'G2' },
    { terminal: 'T1', range: 'AF15:AI15', label: 'G3' },
    { terminal: 'T1', range: 'AJ15:AM15', label: 'G4' },
    { terminal: 'T1', range: 'AN15:AQ15', label: 'G5' },
    { terminal: 'T1', range: 'AR15:AU15', label: 'G6' },
    { terminal: 'T1', range: 'AV15:AY15', label: 'G7' },
    { terminal: 'T1', range: 'X16:AY17', label: 'Зона отгрузки ГП Комплектация / (1 этаж)' },
    { terminal: 'T1', range: 'H18:Q22', label: 'Производство ЛПБ / (2 этаж)' },
    { terminal: 'T1', range: 'X18:AY19', label: 'Столовая / (2 этаж)' },
    { terminal: 'T1', range: 'V20:V22', label: 'G1' },
    { terminal: 'T1', range: 'X20:AY21', label: 'Прачечная, раздевалка ЛБП / (3 этаж)' },
    { terminal: 'T1', range: 'X22:AY22', label: 'D1 /' },
    { terminal: 'T1', range: 'BA22:BD22', label: 'G8' },
    { terminal: 'T1', range: 'H23:Q26', label: 'Цех специй ЛБП / (1 этаж)' },
    { terminal: 'T1', range: 'R23:Z23', label: 'С2' },
    { terminal: 'T1', range: 'AA23:AI23', label: 'С3' },
    { terminal: 'T1', range: 'AK23:AS23', label: 'С4' },
    { terminal: 'T1', range: 'AT23:BB23', label: 'С5' },
    { terminal: 'T1', range: 'BC23:BJ23', label: 'С6' },
    { terminal: 'T1', range: 'R24:Z29', label: 'Склад CU' },
    { terminal: 'T1', range: 'AA24:AI29', label: 'ХК-1 / (1,2,3 этажи)' },
    { terminal: 'T1', range: 'AK24:AS29', label: 'ХК-2 / (1,2,3 этажи)' },
    { terminal: 'T1', range: 'AT24:BB29', label: 'Склад СиМ / (Мука)' },
    { terminal: 'T1', range: 'BC24:BJ25', label: 'ЗПФ (3-этаж)' },
    { terminal: 'T1', range: 'BC26:BJ27', label: 'ЗПФ (2-этаж)' },
    { terminal: 'T1', range: 'H27:Q29', label: 'RnD / (1 этаж)' },
    { terminal: 'T1', range: 'BC28:BF29', label: 'Склад ЗПФ лук, картоф' },
    { terminal: 'T1', range: 'BG28:BJ29', label: 'Уч. Ремон. МК' },
    { terminal: 'T1', range: 'H30:Q30', label: 'В1' },
    { terminal: 'T1', range: 'R30:Z30', label: 'В2' },
    { terminal: 'T1', range: 'AA30:AI30', label: 'В3' },
    { terminal: 'T1', range: 'AK30:AS30', label: 'В4' },
    { terminal: 'T1', range: 'AT30:BB30', label: 'В5' },
    { terminal: 'T1', range: 'BE30:BJ30', label: 'В6' },
    { terminal: 'T1', range: 'H31:L32', label: 'CU Магазин / (1 этаж)' },
    { terminal: 'T1', range: 'M31:Q36', label: 'CU Производство' },
    { terminal: 'T1', range: 'R31:Z36', label: 'Склад CU / (1,2,3 этажи)' },
    { terminal: 'T1', range: 'AA31:AI36', label: 'ХК-3 / (1,2,3 этажи)' },
    { terminal: 'T1', range: 'AK31:AS36', label: 'ХК-4 / (1,2,3 этажи)' },
    { terminal: 'T1', range: 'AT31:BB36', label: 'Склад ТМЦ / (1,2,3 этажи)' },
    { terminal: 'T1', range: 'BC31:BC33', label: 'Лифт г' },
    { terminal: 'T1', range: 'BD31:BJ31', label: 'ЗПФ (3 этаж)' },
    { terminal: 'T1', range: 'BD32:BJ32', label: 'ЗПФ (2 этаж)' },
    { terminal: 'T1', range: 'H33:K35', label: 'CU Производство' },
    { terminal: 'T1', range: 'BD33:BJ34', label: 'ЗПФ (1 этаж)' },
    { terminal: 'T1', range: 'L34:L36', label: 'Лифт г' },
    { terminal: 'T1', range: 'BC34:BC36', label: 'Вход ЗПФ' },
    { terminal: 'T1', range: 'BE35:BJ36', label: 'Склад МК' },
    { terminal: 'T1', range: 'H36:K36', label: 'Вход ЛБП' },
    { terminal: 'T1', range: 'L37:O37', label: 'G1' },
    { terminal: 'T1', range: 'R37:U37', label: 'G2' },
    { terminal: 'T1', range: 'V37:V45', label: 'А1' },
    { terminal: 'T1', range: 'W37:AX37', label: 'A1 /' },
    { terminal: 'T1', range: 'AY37:AY45', label: 'А1' },
    { terminal: 'T1', range: 'AZ37:BB37', label: 'G1' },
    { terminal: 'T1', range: 'BD37:BF37', label: 'G2' },
    { terminal: 'T1', range: 'W38:AX39', label: 'Кабинеты / (3 этаж)' },
    { terminal: 'T1', range: 'W40:AX41', label: 'Кабинеты / (2 этаж)' },
    { terminal: 'T1', range: 'W42:Z44', label: 'Касса' },
    { terminal: 'T1', range: 'AA42:AX43', label: 'Зона отгрузки ГП Региональный / (1 этаж)' },
    { terminal: 'T1', range: 'AA44:AD44', label: 'G1' },
    { terminal: 'T1', range: 'AE44:AH44', label: 'G2' },
    { terminal: 'T1', range: 'AI44:AL44', label: 'G3' },
    { terminal: 'T1', range: 'AM44:AP44', label: 'G4' },
    { terminal: 'T1', range: 'AQ44:AT44', label: 'G5' },
    { terminal: 'T1', range: 'AU44:AX44', label: 'G6' },
    { terminal: 'T1', range: 'G45:K47', label: 'КПП / №1' },
    { terminal: 'T1', range: 'W45:AX45', label: 'A1 /' },
    { terminal: 'T1', range: 'E48:H48', label: 'G1' },

    // T2
    { terminal: 'T2', range: 'R11:BM11', label: 'В3' },
    { terminal: 'T2', range: 'R12:Y12', label: 'Part (блок) 1' },
    { terminal: 'T2', range: 'Z12:AG12', label: 'Part (блок) 2' },
    { terminal: 'T2', range: 'AH12:AO12', label: 'Part (блок) 3' },
    { terminal: 'T2', range: 'AP12:AW12', label: 'Part (блок) 4' },
    { terminal: 'T2', range: 'AX12:BE12', label: 'Part (блок) 5' },
    { terminal: 'T2', range: 'BF12:BM12', label: 'Part (блок) 6' },
    { terminal: 'T2', range: 'R13:BM17', label: 'Расширение' },
    { terminal: 'T2', range: 'R18:BM18', label: 'В3' },
    { terminal: 'T2', range: 'R20:BW20', label: 'В2' },
    { terminal: 'T2', range: 'R21:W21', label: 'Part (блок) 1' },
    { terminal: 'T2', range: 'X21:AC21', label: 'Part (блок) 2' },
    { terminal: 'T2', range: 'AD21:AI21', label: 'Part (блок) 3' },
    { terminal: 'T2', range: 'AJ21:AR21', label: 'Part (блок) 4' },
    { terminal: 'T2', range: 'AS21:AT35', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'AU21:BC21', label: 'Part (блок) 5' },
    { terminal: 'T2', range: 'BD21:BE35', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'BF21:BP21', label: 'Part (блок) 6' },
    { terminal: 'T2', range: 'BQ21:BW21', label: 'Part (блок) 7' },
    { terminal: 'T2', range: 'BX21:BX22', label: 'G3' },
    { terminal: 'T2', range: 'R22:W28', label: 'Кабинеты / (2 этаж)' },
    { terminal: 'T2', range: 'X22:AC35', label: 'Склад роботизированный (высота 1-3 этажи)' },
    { terminal: 'T2', range: 'AD22:AI35', label: 'Зона паллетизации / (высота 1-3 этажи)' },
    { terminal: 'T2', range: 'AJ22:AR35', label: 'Производство МЦ-3' },
    { terminal: 'T2', range: 'AU22:BC23', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'BF22:BP25', label: 'Склад СиМ, Склад CU, Зона РМУ, Мебельный' },
    { terminal: 'T2', range: 'BQ22:BW23', label: 'Кабинеты / 3-этаж' },
    { terminal: 'T2', range: 'Q23:Q25', label: 'G5' },
    { terminal: 'T2', range: 'BX23:BX24', label: 'G2' },
    { terminal: 'T2', range: 'AU24:BC35', label: 'Вафельный цех' },
    { terminal: 'T2', range: 'BQ24:BW25', label: 'Кабинеты / 2-этаж' },
    { terminal: 'T2', range: 'BX25:BX26', label: 'G1' },
    { terminal: 'T2', range: 'BF26:BW27', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'Q27:Q28', label: 'G4' },
    { terminal: 'T2', range: 'BF28:BP35', label: 'Склад СиМ, Склад CU, Зона РМУ, Мебельный' },
    { terminal: 'T2', range: 'BQ28:BW35', label: 'Времено склад оборудования ТМЦ /' },
    { terminal: 'T2', range: 'Q29:Q30', label: 'G3' },
    { terminal: 'T2', range: 'R29:W35', label: 'Зона отгрузки ГП робот' },
    { terminal: 'T2', range: 'BX30:BX31', label: 'G3' },
    { terminal: 'T2', range: 'Q31:Q32', label: 'G2' },
    { terminal: 'T2', range: 'BX32:BX33', label: 'G2' },
    { terminal: 'T2', range: 'Q33:Q34', label: 'G1' },
    { terminal: 'T2', range: 'BX34:BX35', label: 'G1' },
    { terminal: 'T2', range: 'R36:BW36', label: 'В2' },
    { terminal: 'T2', range: 'AE37:AG37', label: 'G3' },
    { terminal: 'T2', range: 'AQ37:AR37', label: 'G2' },
    { terminal: 'T2', range: 'AS37:AT45', label: 'Галерея' },
    { terminal: 'T2', range: 'BA37:BC37', label: 'G1' },
    { terminal: 'T2', range: 'BD37:BE45', label: 'Галерея' },
    { terminal: 'T2', range: 'BR37:BS37', label: 'G1' },
    { terminal: 'T2', range: 'BT37:BU45', label: 'Галерея' },
    { terminal: 'T2', range: 'V38:X38', label: 'G2' },
    { terminal: 'T2', range: 'R39:AA39', label: 'С6' },
    { terminal: 'T2', range: 'AD39:AI39', label: 'С5' },
    { terminal: 'T2', range: 'R40:AA43', label: 'Склад гофрораты' },
    { terminal: 'T2', range: 'AD40:AI43', label: 'АХЦ' },
    { terminal: 'T2', range: 'AM40', label: 'G5' },
    { terminal: 'T2', range: 'AN40', label: 'G6' },
    { terminal: 'T2', range: 'AO40', label: 'G7' },
    { terminal: 'T2', range: 'AP40', label: 'G8' },
    { terminal: 'T2', range: 'Q41:Q42', label: 'G1' },
    { terminal: 'T2', range: 'AC41:AC42', label: 'G1' },
    { terminal: 'T2', range: 'AJ41:AJ42', label: 'G1' },
    { terminal: 'T2', range: 'AM41:AP41', label: 'С4' },
    { terminal: 'T2', range: 'AM42:AP43', label: 'ТП (Трансформаторная)' },
    { terminal: 'T2', range: 'BK43:BP45', label: 'Молокоприемка' },
    { terminal: 'T2', range: 'BQ43:BQ45', label: 'G4' },
    { terminal: 'T2', range: 'AM44', label: 'G1' },
    { terminal: 'T2', range: 'AN44', label: 'G2' },
    { terminal: 'T2', range: 'AO44', label: 'G3' },
    { terminal: 'T2', range: 'AP44', label: 'G4' },
    { terminal: 'T2', range: 'F46:L46', label: 'С7' },
    { terminal: 'T2', range: 'R46:BW46', label: 'В1' },
    { terminal: 'T2', range: 'F47:L52', label: 'ЛОС / (Локальные очистные сооружения)' },
    { terminal: 'T2', range: 'R47:W47', label: 'Part (блок) 1' },
    { terminal: 'T2', range: 'X47:AC47', label: 'Part (блок) 2' },
    { terminal: 'T2', range: 'AD47:AI47', label: 'Part (блок) 3' },
    { terminal: 'T2', range: 'AJ47:AR47', label: 'Part (блок) 4' },
    { terminal: 'T2', range: 'AS47:AT61', label: 'Галерея' },
    { terminal: 'T2', range: 'AU47:BC47', label: 'Part (блок) 5' },
    { terminal: 'T2', range: 'BD47:BE61', label: 'Галерея' },
    { terminal: 'T2', range: 'BF47:BP47', label: 'Part (блок) 6' },
    { terminal: 'T2', range: 'BQ47:BW47', label: 'Part (блок) 7' },
    { terminal: 'T2', range: 'Q48:Q50', label: 'G5' },
    { terminal: 'T2', range: 'R48:W52', label: 'Кабинеты / (2 этаж)' },
    { terminal: 'T2', range: 'X48:AC61', label: 'Склад роботизированный МЦ-3' },
    { terminal: 'T2', range: 'AD48:AI61', label: 'Склад роботизированный МЦ-3' },
    { terminal: 'T2', range: 'AJ48:AR52', label: 'Формирование гофротары' },
    { terminal: 'T2', range: 'AU48:BC59', label: 'Производство МЦ-3' },
    { terminal: 'T2', range: 'BF48:BP49', label: 'Техпомещения (компрессорная)' },
    { terminal: 'T2', range: 'BQ48:BU61', label: 'Склад СиМ / (Высота до 3 этажа) /' },
    { terminal: 'T2', range: 'BV48:BW54', label: 'Кабинеты / 3-этаж' },
    { terminal: 'T2', range: 'BF50:BP51', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'Q51:Q53', label: 'G4' },
    { terminal: 'T2', range: 'BF52:BP56', label: 'Склад СиМ / (Высота до 3 этажа)' },
    { terminal: 'T2', range: 'R53:W61', label: 'Зона отгрузки ГП МЦ-3' },
    { terminal: 'T2', range: 'AJ53:AR57', label: 'Зона паллетизации' },
    { terminal: 'T2', range: 'Q54:Q56', label: 'G3' },
    { terminal: 'T2', range: 'BV55:BW61', label: 'Кабинеты / 2-этаж' },
    { terminal: 'T2', range: 'BX56:BX57', label: 'G3' },
    { terminal: 'T2', range: 'Q57:Q59', label: 'G2' },
    { terminal: 'T2', range: 'BF57:BP58', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'AJ58:AR59', label: 'Склад брака' },
    { terminal: 'T2', range: 'BX58:BX59', label: 'G2' },
    { terminal: 'T2', range: 'BF59:BP61', label: 'Зона маркетинга / 2 этаж / (высокий, третьего этажа нет)' },
    { terminal: 'T2', range: 'Q60:Q61', label: 'G1' },
    { terminal: 'T2', range: 'AJ60:AR61', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'AU60:BC61', label: 'Галерея (внутреняя)' },
    { terminal: 'T2', range: 'BX60:BX61', label: 'G1' },
    { terminal: 'T2', range: 'R62:BW62', label: 'В1' },
    { terminal: 'T2', range: 'AQ63:AR63', label: 'G2' },
    { terminal: 'T2', range: 'AS63:AT69', label: 'Галерея' },
    { terminal: 'T2', range: 'BD63:BE69', label: 'Галерея' },
    { terminal: 'T2', range: 'BF63:BJ63', label: 'G1' },
    { terminal: 'T2', range: 'BU63:BV63', label: 'Вход' },
    { terminal: 'T2', range: 'E65:K65', label: 'А4' },
    { terminal: 'T2', range: 'E66:K66', label: 'Сортировочная АХО' },
    { terminal: 'T2', range: 'E67:E69', label: '1' },
    { terminal: 'T2', range: 'F67:F69', label: '2' },
    { terminal: 'T2', range: 'G67:G69', label: '3' },
    { terminal: 'T2', range: 'H67:H69', label: '4' },
    { terminal: 'T2', range: 'I67:I69', label: '5' },
    { terminal: 'T2', range: 'J67:J69', label: '6' },
    { terminal: 'T2', range: 'K67:K69', label: '7' },
    { terminal: 'T2', range: 'BN69:BO69', label: 'Вход' },
    { terminal: 'T2', range: 'M70:AH70', label: 'А3' },
    { terminal: 'T2', range: 'AJ70:BE70', label: 'А2' },
    { terminal: 'T2', range: 'BF70:BF78', label: 'А2' },
    { terminal: 'T2', range: 'BK70:BK78', label: 'А1' },
    { terminal: 'T2', range: 'BL70:BQ70', label: 'А1' },
    { terminal: 'T2', range: 'BR70:BR78', label: 'А1' },
    { terminal: 'T2', range: 'AJ71:BE71', label: 'Кабинеты 6 этаж' },
    { terminal: 'T2', range: 'BL71:BQ71', label: 'АКНЦ 6 этаж' },
    { terminal: 'T2', range: 'AJ72:BE72', label: 'Кабинеты 5 этаж' },
    { terminal: 'T2', range: 'BL72:BQ72', label: 'АКНЦ 5 этаж' },
    { terminal: 'T2', range: 'AJ73:BE73', label: 'Лаборатория 4 этаж' },
    { terminal: 'T2', range: 'BL73:BQ73', label: 'АКНЦ 4 этаж' },
    { terminal: 'T2', range: 'AJ74:BE74', label: 'Столовая, раздевалки 3 этаж' },
    { terminal: 'T2', range: 'BL74:BQ74', label: 'БиОТ и HR 3 этаж' },
    { terminal: 'T2', range: 'AJ75:BE75', label: 'Столовая, раздевалки 2 этаж' },
    { terminal: 'T2', range: 'BL75:BQ75', label: 'HR Кадры 2 этаж' },
    { terminal: 'T2', range: 'AJ76:BE77', label: 'Столовая для уличный, раздевалки / 1 этаж' },
    { terminal: 'T2', range: 'BL76:BQ77', label: 'КПП- Турникеты / 1 этаж' },
    { terminal: 'T2', range: 'M78:AH78', label: 'А3' },
    { terminal: 'T2', range: 'AJ78:BE78', label: 'А2' },
    { terminal: 'T2', range: 'BG78:BJ79', label: 'Въезд (светофор)' },
    { terminal: 'T2', range: 'BL78:BQ78', label: 'А1' },
    { terminal: 'T2', range: 'V79:W79', label: 'G2' },
    { terminal: 'T2', range: 'AT79:AU79', label: 'G2' },
    { terminal: 'T2', range: 'BN79:BO79', label: 'Вход' },

    // T3
    { terminal: 'T3', range: 'Q7:U14', label: 'С1 / Пикинг мороженого' },
    { terminal: 'T3', range: 'X7:AB14', label: 'С2 / (Сегмента 1)' },
    { terminal: 'T3', range: 'AE7:AI14', label: 'С3 / (Сегмента 2)' },
    { terminal: 'T3', range: 'AL7:AP14', label: 'С4 / (Склад CU)' },
    { terminal: 'T3', range: 'AS7:AW14', label: 'С5 / (Производство CU )' },
    { terminal: 'T3', range: 'AZ7:BD14', label: 'С6 / (Склад строй материалов и оборудования CU)' },
    { terminal: 'T3', range: 'BG7:BK14', label: 'С7 / (Склад МК, Цех по ремонту МК ларей и бытовой техники)' },
    { terminal: 'T3', range: 'BN7:BR14', label: 'С8 / (Производство и ремонт поддонов)' },
    { terminal: 'T3', range: 'BU7:BY14', label: 'С9 / (Мебельный цех )' },
    { terminal: 'T3', range: 'BO18', label: 'Склад по строительству-выпал из-за Сегменты 2' },
    { terminal: 'T3', range: 'Q19:U26', label: 'В1 / Дэсанг' },
    { terminal: 'T3', range: 'X19:AB26', label: 'В2 / (Свободно)' },
    { terminal: 'T3', range: 'AE19:AI26', label: 'В3 / (Свободно)' },
    { terminal: 'T3', range: 'AL19:AP26', label: 'В4 / (Склад гофротары)' },
    { terminal: 'T3', range: 'AS19:AW26', label: 'В5 / (Склад ТМЦ Основной)' },
    { terminal: 'T3', range: 'AZ19:BD26', label: 'В6 / (Мастерская)' },
    { terminal: 'T3', range: 'BG19:BK26', label: 'В7 / (Сварочный участок)' },
    { terminal: 'T3', range: 'T28:AE43', label: 'А2 / (CU Производство и РЦ)' },
    { terminal: 'T3', range: 'P46:R49', label: 'А1 Рембокс' },
] as const;
